[package]
name = "gmtk2024"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = {version="0.14.1", features=["wav"]}
bevy_mod_picking = "0.20.1"
